"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import test1

# Implementing MyFrame1
class MyClassMyFrame1( test1.MyFrame1 ):
	def __init__( self, parent ):
		test1.MyFrame1.__init__( self, parent )

